### ISSUE TITLE
Starting the proxy for development with a react server fails.

### ISSUE THREAD

**Issue by potamides** [tdelta/SynergyQuest#19]
Starting the proxy for development with a react server fails with the following error:
```
(node:152790) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time                                      
(Use `node --trace-warnings ...` to show where the warning was created)                                                                                         
TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected string to be returned for the "format" from the "loader getFormat" function but got type object.        
    at Loader.getFormat (internal/modules/esm/loader.js:110:13)                                                                                                 
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:20)                                                                                              
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:53:21)                                                                                        
    at async Promise.all (index 2)                                                                                                                              
    at link (internal/modules/esm/module_job.js:58:9)                                                                                                           
error Command failed with exit code 1.                                          
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This problem seems to have been introduced with node 14.13.1. Older versions work fine, so the current workaround is to downgrade to 14.13.0. More information can be found [here](https://github.com/TypeStrong/ts-node/issues/1007#issuecomment-706684853).

**Comment by ahbnr** [comment]
Fixed by f351447430af32d32e4b1ec1d543d5f4c3f0af18

Node downgrade not necessary.
